spring.application.name=TpIntegrado
server.port=${PORT:8083}

# BASE DE DATOS - Lee variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# créate-drop: borra y recrea tablas en cada deploy
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para que data.sql se ejecute DESPUÉS de crear tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Configuración de swagger y apidocs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs